### ISSUE TITLE
Does your widget work on the web at the same time that the application's javascript is loading? 

### ISSUE THREAD

**Issue by Josua2012** [watery-desert/loading_animation_widget#2]
Hi,

Does your widget work on the web at the same time that the application's javascript is loading? 

Thanks.
Regards,
Jose

**Comment by watery-desert** [comment]
I have no idea how javascript loads in the background when you use Flutter. You can give me a code snippet so I can confirm. In genera,l when you do some async task you can show the loading animaiton until it finishes. More specifically, this package is alternative to [flutter CircularProgressIndicator widget](https://api.flutter.dev/flutter/material/CircularProgressIndicator-class.html) with more variety.

**Comment by watery-desert** [comment]
closing because of no reply.
