### ISSUE TITLE
question: Widget size

### ISSUE THREAD

**Issue by S-ecki** [watery-desert/loading_animation_widget#4]
First of all, lovely animations!

I was using the built in `CircularProgressIndicator` and shifted to your packages, which looks awesome! 
The only problem I have is that the built in Indicator sized itself according to the constraints (as far as I can tell without looking deep into the code).
For your widget, a size has to be set manually. Setting it to a sensible default value leads to "jumping" of entries in my `ListView` if some entry shows the loading widget and then the actual content.
Often times it is tedious to get the available height and then set the size of your loading widget to it. Is there a leaner way to do this?

**Comment by watery-desert** [comment]
Yes `CircularProgressIndicator` has fixed `minWidth` and `minHeight` constraints. For this package this won't work I have so many different types of animations and I need a fixed size 😞 For some animations the provided size is outer bound then there is an `innerSize` to keep the animation within.

**Comment by S-ecki** [comment]
I understand, thanks for the fast answer and the package! ❤
