### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by zachary22321** [watery-desert/loading_animation_widget#5]
This code caused a memory leak for me, which went away whenI rmeoved the LoadingAnimationWidget

 ```
AnimatedOpacity(
                  opacity: isUpdating ? 1.0 : 0.0,
                  duration: isUpdating
                      ? const Duration(milliseconds: 0)
                      : const Duration(milliseconds:500),
                  child: Row(
                    children: [
                      LoadingAnimationWidget.fourRotatingDots(
                        color: Colors.black12,
                        size: 20,
                      ),
                      SizedBox(
                        width: 3,
                      ),
                      Text(
                        "Saving...",
                        style: TextStyle(color: Colors.grey.shade600),
                      ),
                    ],
                  ),
```

**Comment by watery-desert** [comment]
This issue is not related to `LoadingAnimationWidget`. When `isUpdating` is false `LoadingAnimationWidget`is in the widget tree and still animating. I can do nothing. You shouldn't dynamically change the opacity of animating widget. Instead, remove it from the widget tree.

**Comment by zachary22321** [comment]
It's a list of 25 items, even if it was in the tree and visible, it should not be creating a memory leak of that size and power. I would open the listview and leave it there without touching it and the application would enter into a run away memory leak until all of the memory was gone. I've worked around it now, but I wanted to bring it to your attention. Thanks for taking the time to comment.
